### PR TITLE
Throw error during build script if data type is incorrect

### PR DESCRIPTION
**Pull request by dustin-phantom**
this PR adds a filtering step during build to ensure that urls and nft mints are strings

### CODE REVIEW

**Comment by fragosti** [comment]
I don't think we want to filter but fail, right? This will just fail silently and lead to other problems.

**Comment by dustin-phantom** [comment]
> I don't think we want to filter but fail, right? This will just fail silently and lead to other problems.

Good call @fragosti, updated to throw error

**Comment by fragosti** [comment]
This should work. I wonder if a linter like https://github.com/adrienverge/yamllint will get us farther but this fixes the issue

**Comment by fragosti** [comment]
Why not on the fuzzy list?

**Comment by dustin-phantom** [comment]
> Why not on the fuzzy list?

The fuzzy list is currently blank, so not sure what shape the data will look like https://github.com/phantom/blocklist/blob/master/fuzzylist.yaml

**Comment by fragosti** [comment]
Would add to the fuzzylist and then whoever eventually adds can deal with it.

**Comment by dustin-phantom** [comment]
> Would add the URL checker to the fuzzylist and then whoever eventually adds can deal with it.

Updated

**Comment by fragosti** [comment]
So what happens when someone submits a bad PR now? I'm not sure they would actually get notified. Need to update CI, or use the linter.

**Comment by dustin-phantom** [comment]
> So what happens when someone submits a bad PR now? I'm not sure they would actually get notified. Need to update CI, or use the linter.

Okay I learned in the post mortem that there is formatting in place and the bad commit did throw an error https://github.com/phantom/blocklist/actions/runs/7174818855/job/19536983321. However it did not block the merge. Security is gonna update the repo to block the merge. So not sure if we still want these steps in place?

**Comment by fragosti** [comment]
> > So what happens when someone submits a bad PR now? I'm not sure they would actually get notified. Need to update CI, or use the linter.
> 
> Okay I learned in the post mortem that there is formatting in place and the bad commit did throw an error https://github.com/phantom/blocklist/actions/runs/7174818855/job/19536983321. However it did not block the merge. Security is gonna update the repo to block the merge. So not sure if we still want these steps in place?

Just close this

**Pull request closed without merging**
