### PR TITLE
Removing Doggyonsol from blocklist - it is not a scam

### PR DESCRIPTION
**Pull request by GratefulAmadeus**
Removed this site from the blocklist as it is not a scam.

Twitter: https://twitter.com/DoggyinSol

Just spoke with the project creators and have verified it is not a scam - please let me know if you need other info.

### CODE REVIEW

**Comment by MYRoandrew** [comment]
The website is Doggyonsol.com

**Comment by GratefulAmadeus** [comment]
@MYRoandrew correct, if you go to the Twitter link, you can see that's the site they have listed

**Comment by Harii94** [comment]
@GratefulAmadeus We have received a report that these guys are serial scammers and they just changed their Telegram name. Their old projects: Anitaonsol, saturnonsol. Same pattern, same designs.

I'm sorry I won't be able to unblock them.

**Comment by GratefulAmadeus** [comment]
Understood, thanks for checking it out

**Pull request closed without merging**
